### ISSUE TITLE
if condition for flash_attention_with_fusing_bias_varlen is opposite

### ISSUE THREAD

**Issue by issacqzh** [Knowledgator/TurboT5#3]
Thanks for the implementation of flash attention for T5. I'm wondering if this [line](https://github.com/Knowledgator/TurboT5/blob/main/src/turbot5/model/attentions.py#L485) should be `if not varlen`

**Comment by Ingvarstep** [comment]
Thank you for pointing out this issue! You are right, so I just fixed it.
